FROM centos:6

MAINTAINER soarpenguin "soarpenguin@gmail.com"

RUN yum install -y passwd \
    openssh \
    openssh-server \
    openssh-clients \
    sudo

RUN sed -ri "s/^UsePAM yes/#UsePAM yes/" /etc/ssh/sshd_config && \
    sed -ri "s/^#UsePAM no/UsePAM no/" /etc/ssh/sshd_config

RUN /etc/init.d/sshd start && \
    /etc/init.d/sshd stop && \
    echo "root:dgj99349" | chpasswd

EXPOSE 22 443

CMD ["/usr/sbin/sshd", "-D"]
