#!/usr/bin/env bash

####function
if [ -t 1 ]
then
    RED="$( echo -e "\e[31m" )"
    HL_RED="$( echo -e "\e[31;1m" )"
    HL_BLUE="$( echo -e "\e[34;1m" )"

    NORMAL="$( echo -e "\e[0m" )"
fi

#
# Only use sudo if already root.
#
if (( $UID == 0 )); then
    sudo=""
else
    sudo="sudo"
fi

_hl_red()    { echo "$HL_RED""$@""$NORMAL";}
_hl_blue()   { echo "$HL_BLUE""$@""$NORMAL";}

_trace() {
    echo $(_hl_blue '  ->') "$@" >&2
}

_print_fatal() {
    echo $(_hl_red '==>') "$@" >&2
}

_fatal() {
    echo $(_hl_red '==>') "$@" >&2
    exit 1
}

function install_packages()
{
	case "$package_manager" in
		apt)	$sudo apt-get install -y $* || return $? ;;
		yum)	$sudo yum install -y $* || return $?     ;;
		port)   $sudo port install $* || return $?       ;;
		brew)
			local brew_owner="$(/usr/bin/stat -f %Su "$(command -v brew)")"
			sudo -u "$brew_owner" brew install $* ||
			sudo -u "$brew_owner" brew upgrade $* || return $?
			;;
		pacman)
			local missing_pkgs="$(pacman -T $*)"

			if [[ -n "$missing_pkgs" ]]; then
				$sudo pacman -S $missing_pkgs || return $?
			fi
			;;
		"")	_fatal "Could not determine Package Manager. Proceeding anyway." ;;
	esac
}

########## main route ############
for cmd in apt-get yum port brew pacman; do
    if command -v $cmd >/dev/null; then
        package_manager="$cmd"
        break
    fi
done

## check ruby env
result=`which ruby`
if [ "x$result" = 'x' ]; then
    _trace "ruby is not installed, now install ruby."
    install_packages "ruby" "rubygems"

    if [ $? -eq 0 ]; then
        _trace "install ruby successed."
    else
        _fatal "install ruby failed!"
    fi
else
    version=`ruby --version`
    _trace "ruby is installed. version: $version"
fi

_trace "add source of ruby https://ruby.taobao.org/."
result=`gem sources --remove https://rubygems.org/`
result=`gem sources -a https://ruby.taobao.org/`
_trace "gem suouces add result: $result"
#gem sources -l

#sudo gem install cocoapods
export GEM_HOME=$HOME/.gem
export PATH=$GEM_HOME/bin:$PATH

gem which cocoapods &> /dev/null

ret=$?
if [ x"$ret" != "x0" ]; then
    gem install cocoapods --user-install
    if [ $? -ne 0 ]; then
        _fatal "install cocoapods failed!"
    else
        _trace "install cocoapods successed."
    fi
else
    _trace "cocoapods already installed successed."
fi

