#!/usr/bin/env bash

#set -x
export PS4='+ [`basename ${BASH_SOURCE[0]}`:$LINENO ${FUNCNAME[0]} \D{%F %T} $$ ] '
CURDIR=$(cd "$(dirname "$0")"; pwd)

# set file path
NGINX_ACCESS_LOG="${CURDIR}/logs/nginx-access.log"
NGINX_ERROR_LOG="${CURDIR}/log/nginx-error.log"

# rename log
mv $NGINX_ACCESS_LOG $NGINX_ACCESS_LOG.`date -d yesterday +%Y%m%d`
mv $NGINX_ERROR_LOG $NGINX_ERROR_LOG.`date -d yesterday +%Y%m%d`

touch $NGINX_ACCESS_LOG
touch $NGINX_STATIS_LOG

#/etc/init.d/syslog-ng restart
# restart nginx
#[ ! -f /opt/nginx/logs/nginx.pid ] || kill -USR1 $(cat /opt/nginx/logs/nginx.pid)
${CURDIR}/nginx_control reload
